name: 游냍 Buggrapport / Bug Report
description: Rapportera ett tekniskt problem eller bugg
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Tack f칬r att du rapporterar en bugg! Din feedback hj칛lper oss att f칬rb칛ttra projektet.
        
  - type: textarea
    id: description
    attributes:
      label: Beskrivning av problemet
      description: Beskriv tydligt vad som gick fel
      placeholder: N칛r jag klickar p친 X s친 h칛nder Y ist칛llet f칬r Z...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steg f칬r att reproducera
      description: Vilka steg beh칬vs f칬r att 친terskapa problemet?
      placeholder: |
        1. G친 till '...'
        2. Klicka p친 '...'
        3. Scrolla till '...'
        4. Se felet
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: F칬rv칛ntat beteende
      description: Vad f칬rv칛ntade du dig skulle h칛nda?
      placeholder: Jag f칬rv칛ntade mig att...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Faktiskt beteende
      description: Vad h칛nde ist칛llet?
      placeholder: Ist칛llet h칛nde...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Milj칬
      description: Vilken milj칬 anv칛nder du?
      placeholder: |
        - OS: [t.ex. Windows 11, macOS 14, Ubuntu 22.04]
        - Webbl칛sare: [t.ex. Chrome 120, Firefox 121, Safari 17]
        - Version: [t.ex. 1.0.0]
      value: |
        - OS: 
        - Webbl칛sare: 
        - Version: 
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: Sk칛rmdumpar / Screenshots
      description: L칛gg till sk칛rmdumpar om det hj칛lper att f칬rklara problemet
      placeholder: Dra och sl칛pp bilder h칛r...
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Konsolloggar / Console Logs
      description: Om till칛mpligt, inkludera relevanta felmeddelanden fr친n webbl칛sarens konsol (F12)
      placeholder: Klistra in felmeddelanden h칛r...
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Ytterligare information
      description: N친got annat som kan vara relevant?
      placeholder: Eventuell extra kontext...
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Kontrollpunkter
      description: Bekr칛fta f칬ljande innan du skickar
      options:
        - label: Jag har s칬kt efter liknande issues och hittade inga dubbletter
          required: true
        - label: Detta 칛r en bugg i koden, inte en s칛kerhetsbugg (f칬r s칛kerhetsproblem, se SECURITY.md)
          required: true
        - label: Jag anv칛nder den senaste versionen av projektet
          required: false
