name: 游눫 Fr친ga / Question
description: St칛ll en fr친ga om projektet
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        V칛lkommen att st칛lla fr친gor om projektet! Vi hj칛lper g칛rna till.
        
  - type: textarea
    id: question
    attributes:
      label: Din fr친ga / Your Question
      description: Vad vill du veta?
      placeholder: Hur anv칛nder jag...? Varf칬r 칛r...? Kan systemet...?
    validations:
      required: true
      
  - type: dropdown
    id: topic
    attributes:
      label: 츿mnesomr친de / Topic
      description: Vilket omr친de handlar fr친gan om?
      options:
        - Komma ig친ng / Getting Started
        - Anv칛ndning / Usage
        - Konfiguration / Configuration
        - Integration
        - Teoretisk grund / Theoretical Framework
        - GIRFEC / SHANARRI
        - ICF-klassificering / ICF Classification
        - Semantisk mappning / Semantic Mapping
        - Deployment
        - S칛kerhet / Security
        - Dokumentation
        - Bidra till projektet / Contributing
        - 칐vrigt / Other
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Kontext / Context
      description: Ge oss lite bakgrund om din situation
      placeholder: Jag f칬rs칬ker anv칛nda systemet f칬r... Min organisation 칛r...
    validations:
      required: false
      
  - type: textarea
    id: research
    attributes:
      label: Vad har du provat? / What Have You Tried?
      description: Har du f칬rs칬kt hitta svaret i dokumentationen eller tidigare issues?
      placeholder: Jag har l칛st... Jag har provat att...
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Kontrollpunkter / Checklist
      options:
        - label: Jag har l칛st README.md
          required: false
        - label: Jag har s칬kt i befintliga issues efter liknande fr친gor
          required: false
        - label: Detta 칛r inte en s칛kerhetsfr친ga (f칬r s칛kerhet, se SECURITY.md)
          required: true
